---
title: "Some things I learned this quarter"
subtitle: "Fish 549"
author: "Callum Backstrom<br>callumhb@uw.edu"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Introduction

## About Me | Personal

- <b>Birth State/Country</b>: Pennsylvania, United States
- <b>Favorite Foods</b>: Gyoza, Lemon Squares, Outback Steakhouse Bloomin Onion
- <b>Favorite Animals</b>: Corals, Octopuses, Parrots, Axlotls, Boxfish, 
Velvet Worms, Tapirs


## About Me | Academic

- <b>Undergraduate Institution</b>: Dartmouth College
- <b>Undergraduate Major</b>: Biology (Focus: Ecology)

# Data Science

## Course Topics | 3 things I enjoyed learning about
    1) How to "pull" and "push" R and Rmd files via Github for collaborations   
    2) How to convert my Microsoft Word-centric manuscripts, proposals, etc. 
    into interactive Rmd files/PDFs
    3) How to create my own R package and describe its functions/uses
    
## Course Topics | 3 things I’d like to learn more about
    1) How to build/use Shiny Apps for my own research needs   
    2) How to integrate AGILE methods into my own work with my lab and our 
    projects
    3) How to organize maintenance of R packages created by a team of people 
    including yourself (i.e., responsibilities, responsiveness to feedback, 
    etc.)
    
## {data-background=img/CCMI_LittleCayman.jpg data-background-size=cover}